### ISSUE TITLE
SystemStackError: stack level too deep

### ISSUE THREAD

**Issue by pacolotero** [errbit/errbit#1017]
Upgrading Errbit i get this error when rake db:migrate
```
==  ExtractIssueTracker: migrating ============================================
rake aborted!
SystemStackError: stack level too deep

Tasks: TOP => db:migrate
(See full trace by running task with --trace)

```

Here all trace:
```
** Invoke db:migrate (first_time)
** Invoke environment (first_time)
** Execute environment
** Execute db:migrate
==  ExtractIssueTracker: migrating ============================================
rake aborted!
SystemStackError: stack level too deep
/home/errbit/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb:183
Tasks: TOP => db:migrate

```

/home/errbit/.rvm/gems/ruby-2.1.6/gems/rake-10.4.2/lib/rake/task.rb
 ```
# Same as invoke, but explicitly pass a call chain to detect
    # circular dependencies.
    def invoke_with_call_chain(task_args, invocation_chain) # :nodoc:
      new_chain = InvocationChain.append(self, invocation_chain)
      @lock.synchronize do
        if application.options.trace
          application.trace "** Invoke #{name} #{format_trace_flags}"
        end
        return if @already_invoked
        @already_invoked = true
        invoke_prerequisites(task_args, new_chain)
        execute(task_args) if needed?
      end
    rescue Exception => ex
      add_chain_to(ex, new_chain)
      raise ex # Line 183
    end
 ```

$ rake db:version
**2015052720262**

RUBY
 ```
    version:      "2.1.6p336"
    date:         "2015-04-13"
    platform:     "x86_64-linux"
    patchlevel:   "2015-04-13 revision 50298"
    full_version: "ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-linux]"
 ```

**Comment by stevecrozz** [comment]
Can you attempt to get a stack trace from this rake task by adding --trace to the failing command?

**Comment by darthrevan** [comment]
I've encountered the same issue.
Turned out that this error was caused by 
```
App.all
```
in the migration. Furthermore, 
```
App.first
```
or any other references to this model resulted in "stack level too deep" error.
 

I was able to solve it by setting store_in 'apps2' and running rails console - got an empty collection that worked just fine.
Then I removed this line and run rails console again. Then I checked all other models - they were fine too. Strangely, but after doing all this I was able to access the old apps collections and migration run fine.

Yeah I know it's magic but maybe it will help you.

**Comment by stevecrozz** [comment]
@darthrevan You didn't save a full stack trace by any chance, did you?

**Comment by dennmart** [comment]
Not sure if this is the same issue, but I'm also getting "stack level too deep" error after upgrading. I'm hosting my instance of Errbit on Heroku. It was running v0.4.0 fine, and when I upgraded to v0.5.0, that's when I began getting the error after logging in. Here's a stacktrace of what I'm running into - hopefully it helps: https://gist.github.com/dennmart/45d11e1661991ebe0991

**Comment by darthrevan** [comment]
@stevecrozz yeah sure.
```
irb(main):001:0> App.first
SystemStackError: stack level too deep
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/socket.rb:172:in `read_from_socket'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/socket.rb:123:in `block in read'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/socket.rb:191:in `handle_errors'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/socket.rb:122:in `read'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/bson-3.2.4/lib/bson/hash.rb:76:in `from_bson'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/dbref.rb:103:in `from_bson'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/protocol/serializers.rb:166:in `deserialize'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/protocol/message.rb:234:in `block in deserialize_array'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/protocol/message.rb:234:in `times'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/protocol/message.rb:234:in `deserialize_array'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/protocol/message.rb:87:in `block in deserialize'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/protocol/message.rb:85:in `each'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/protocol/message.rb:85:in `deserialize'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/server/connection.rb:171:in `block in ping'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/server/connectable.rb:91:in `ensure_connected'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongo-2.1.1/lib/mongo/server/connection.rb:169:in `ping'
... 8884 levels...
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:503:in `call'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/callbacks.rb:88:in `run_callbacks'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/interceptable.rb:138:in `run_callbacks'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/persistable/creatable.rb:23:in `insert'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/mongoid-5.0.0/lib/mongoid/persistable/savable.rb:23:in `save'
	from (irb):10
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:110:in `start'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/console.rb:9:in `start'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/ubuntu/errbit/shared/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:6:in `require'
	from bin/rails:6:in `<main>'irb(main):011:0> quit
```

Running the migration itself yield exactly the same stack trace as @dennmart - I encountered the issue with the model itself while running the migration code line by line manually.

I was upgrading Errbit from 0.3 to 0.5 if it helps.

**Comment by stevecrozz** [comment]
Thanks everyone. I was able to reproduce this issue and I added a fix to master. This should be solved.

**Comment by kumarks1122** [comment]
Changing the ruby version did the trick for me
