### ISSUE TITLE
Deploy To Heroku button is broken

### ISSUE THREAD

**Issue by alexkojin** [errbit/errbit#1127]
I've tried to install errbit using "Deploy To Heroku" button form this page [https://github.com/errbit/errbit/blob/master/docs/deployment/heroku.md](https://github.com/errbit/errbit/blob/master/docs/deployment/heroku.md) and got next error.

```
 Cleaning up the bundler cache.
sh: 2: Syntax error: Unterminated quoted string
sh: 2: Syntax error: Unterminated quoted string
 !
 !     Could not detect rake tasks
 !     ensure you can run `$ bundle exec rake -P` against your app
 !     and using the production group of your Gemfile.
 !     rake aborted!
 !     LoadError: cannot load such file -- phantomjs/poltergeist
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/config/application.rb:10:in `<top (required)>'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/Rakefile:11:in `require'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/Rakefile:11:in `<top (required)>'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
 !     /tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
 !     vendor/bundle/bin/rake:16:in `load'
 !     vendor/bundle/bin/rake:16:in `<main>'
 !
/app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/helpers/rake_runner.rb:102:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
ensure you can run `$ bundle exec rake -P` against your app
and using the production group of your Gemfile.
rake aborted!
LoadError: cannot load such file -- phantomjs/poltergeist
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `require'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:77:in `block (2 levels) in require'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `each'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:72:in `block in require'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `each'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler/runtime.rb:61:in `require'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/bundler-1.11.2/lib/bundler.rb:99:in `require'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/config/application.rb:10:in `<top (required)>'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/Rakefile:11:in `require'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/Rakefile:11:in `<top (required)>'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/rake_module.rb:28:in `load_rakefile'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:689:in `raw_load_rakefile'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:94:in `block in load_rakefile'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:93:in `load_rakefile'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:77:in `block in run'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:176:in `standard_exception_handling'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/lib/rake/application.rb:75:in `run'
/tmp/build_560f3a137a5e7849f06f8108a384b33f/errbit-errbit-93ac693/vendor/bundle/ruby/2.2.0/gems/rake-10.5.0/bin/rake:33:in `<top (required)>'
vendor/bundle/bin/rake:16:in `load'
vendor/bundle/bin/rake:16:in `<main>'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/ruby.rb:746:in `rake'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails4.rb:77:in `block (2 levels) in run_assets_precompile_rake_task'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:131:in `log'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails4.rb:71:in `block in run_assets_precompile_rake_task'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails4.rb:70:in `run_assets_precompile_rake_task'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/ruby.rb:104:in `block (2 levels) in compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/ruby.rb:767:in `allow_git'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/ruby.rb:98:in `block in compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/ruby.rb:88:in `compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails2.rb:49:in `block in compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails2.rb:47:in `compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails3.rb:38:in `block in compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails3.rb:37:in `compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails4.rb:41:in `block in compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:48:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:44:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/rails4.rb:40:in `compile'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/bin/compile:16:in `block (2 levels) in <main>'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/base.rb:131:in `log'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/bin/compile:15:in `block in <main>'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:35:in `block in trace'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/vendor/ruby-2.3.1/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:16:in `instrument'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/lib/language_pack/instrument.rb:35:in `trace'
	from /app/tmp/buildpacks/f6d48d8a14fccbb19c0c0402fca224929d18e9ee042b3e204bc5992612e990d3b3a0fb1f9627b1a3bae11e9fa20dffc96e136bd734a2f3cf92a0d05bedd42cfe/bin/compile:11:in `<main>'
 !     Push rejected, failed to compile Ruby app.
 !     Push failed
```

**Comment by stevecrozz** [comment]
Thanks for the report @alexkojin. I'm working on a fix at : https://github.com/errbit/errbit/pull/1128

**Comment by stevecrozz** [comment]
Just tested it myself. You should be good to go!

**Comment by alexkojin** [comment]
Thanks!
