### ISSUE TITLE
Undefined method (page/total_pages) on all pages with pagination

### ISSUE THREAD

**Issue by Elsopuro** [errbit/errbit#1166]
mongodb version v3.4.2
errbit - master branch

http://take.ms/LotV4

NoMethodError (undefined method `page' for #<Mongoid::Criteria:0x00000007eb8938>):
  app/controllers/problems_controller.rb:43:in `show'

Processing by UsersController#index as HTML
  Rendered users/index.html.haml within layouts/application (2.4ms)
Completed 500 Internal Server Error in 6ms
Internal error was logged to 'Self.Errbit' app.

ActionView::Template::Error (undefined method `page' for #<Mongoid::Criteria:0x000000078d68a8>):
    16:       %th.main= t('.email')
    17:       %th= t('.admin')
    18:   %tbody
    19:     - users.each do |user|
    20:       %tr.user_list
    21:         - if Errbit::Config.use_gravatar
    22:           %td= gravatar_tag user.email, :s => 24
  app/controllers/users_controller.rb:7:in `block in <class:UsersController>'
  app/views/users/index.html.haml:19:in `_app_views_users_index_html_haml___893793109542355010_33922080'

**Comment by cromulus** [comment]
FWIW, I have the same problem.

**Comment by stevecrozz** [comment]
@cromulus are you also using mongo 3.4.2? I haven't taken the time to look at this yet, just collecting data atm.

**Comment by cromulus** [comment]
mongo 3.2.9

Currently running Errbit inside of Dokku

**Comment by cromulus** [comment]
FYI, have the same problem on another, brand new installation.

**Comment by cromulus** [comment]
Adding `gem 'kaminari-mongoid'` to your gem file fixes this.

**Comment by micred** [comment]
Same problem here, but adding kaminari-mongoid doesn't fix.
Please do a diff with upstream/master and tell us if there are other changes needed.
Thank you

**Comment by cromulus** [comment]
@micred I also apparently ran a `bundle update` as well.
