### ISSUE TITLE
Sending notifications via Airbrake API with Java client not working

### ISSUE THREAD

**Issue by maxper75** [errbit/errbit#1203]
Hi,
I'm trying to send notifications to errbit using the official java airbrake api, without success.
After solving SSL problems (I use letsencrypt CA), now I have a big problem connected with the matter that I fire, using Airbrake API, the contents in XML format, while the errbit api expects it in json, for what I could understand from the log.
what am I doing of wrong?
This is the output in the log
```
https://<myhostname>Started POST "/api/v3/projects/1/notices?key=<mysecretkey>?key=<mysecretkey>" for <myip> at 2017-06-28 13:33:05 +0200
Started POST "/api/v3/projects/1/notices?key=<mysecretkey>?key=<mysecretkey>" for <myip> at 2017-06-28 13:33:05 +0200
Processing by Api::V3::NoticesController#create as XML
Processing by Api::V3::NoticesController#create as XML
  Parameters: {"key"=>"<mysecretkey>?key=<mysecretkey>", "project_id"=>"1"}
  Parameters: {"key"=>"<mysecretkey>?key=<mysecretkey>", "project_id"=>"1"}
Completed 500  in 1ms
Completed 500  in 1ms

JSON::ParserError (lexical error: invalid char in json text.
                                       <?xml version="1.0"?><notice ve
                     (right here) ------^
):
  app/controllers/api/v3/notices_controller.rb:16:in `create'



JSON::ParserError (lexical error: invalid char in json text.
                                       <?xml version="1.0"?><notice ve
                     (right here) ------^
):
  app/controllers/api/v3/notices_controller.rb:16:in `create'
```
while here is the java code I used to send that notification
```
	AirbrakeNotice notice = new AirbrakeNoticeBuilder(
				"<mysecretkey>", e, "<myEnvironment>")
						.newNotice();
		AirbrakeNotifier notifier = new AirbrakeNotifier(
				"https://<myhostname>/api/v3/projects/1/notices?key=<mysecretkey>");
		notifier.notify(notice);
```

where e is the Throwable object I should report, but for what I can understand this is (still?) not the point, as I'm sending things someway that errbit doesn't understand.
Any help would be appreciated, before I start writing another client...

**Comment by stevecrozz** [comment]
Well this is interesting. I haven't used this library, but it l can tell you that Errbit's V3 endpoint does not support XML for error notices. There is an older API you can use to deliver XML notices and path for that is /notifier_api/v2/notices. So that may be a quick fix option.

If you have the flexibility, though, I'd recommend using the newer API (the path you're currently using) with JSON formatted payloads because its my impression that we have more folks using this endpoint and I think you'll have a better experience assuming you can find a client to do it or write your own.

If you need it a reference, Airbrake maintains one: https://airbrake.io/docs/api/#error-notification-v3

**Comment by johnmcconnell** [comment]
FYI, I would be a bit skeptical of the "java" airbrake client. I have used it myself and have encountered a few bugs. For example, https://github.com/airbrake/airbrake-java/pull/52

**Comment by alexmreis** [comment]
@maxper75 You're using the wrong errbit url. You have to append `/notifier_api/v2/notices` to the URL you give to AirbrakeNotifier. This java cient seems to not have been updated to version 3 and beyond of the airbrake API, and Airbrake's website no longer even mentions its existence. They've abandoned Java for greener pastures like Python and Node.js

**Comment by kohenkatz** [comment]
@maxper75 In addition to what @alexmreis said, you are also setting the API key in the URL but the notifier is adding it *again* after that, causing the API key to appear in the request URL twice and to be parsed improperly.

**Comment by alexmreis** [comment]
Just a heads up about https://github.com/airbrake/javabrake which seems to be their new, supported client going forward, and uses the JSON API instead of the (deprecated) XML API.  You should probably switch @maxper75

**Comment by rud** [comment]
Good hint @alexmreis - hope this resolves your issue @maxper75. Closing this issue due to inactivity, thank you all involved.
