### ISSUE TITLE
Issue with errbit cleanup

### ISSUE THREAD

**Issue by compengsamit** [errbit/errbit#1254]
I have upgraded errbit with the steps provided in https://github.com/errbit/errbit/ and after that errbit:cleanup is failing with the below error:
```
[07:46][username@hostname:errbit(master)]$ bundle exec rake errbit:cleanup
Overwriting existing field _id in class App.
Creating scope :page. Overwriting existing method NotificationServices::CampfireService.page.
Creating scope :page. Overwriting existing method NotificationServices::FlowdockService.page.
Creating scope :page. Overwriting existing method NotificationServices::GtalkService.page.
Creating scope :page. Overwriting existing method NotificationServices::HipchatService.page.
Creating scope :page. Overwriting existing method NotificationServices::HoiioService.page.
Creating scope :page. Overwriting existing method NotificationServices::HubotService.page.
Creating scope :page. Overwriting existing method NotificationServices::PushoverService.page.
Creating scope :page. Overwriting existing method NotificationServices::SlackService.page.
Creating scope :page. Overwriting existing method NotificationServices::WebhookService.page.
rake aborted!
NoMethodError: undefined method `uncache_notice' for nil:NilClass
/mnt/username/installs/errbit/app/models/notice.rb:123:in `problem_recache'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:432:in `block in make_lambda'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:164:in `block in halting'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `block in call'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:504:in `call'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778:in `_run_destroy_callbacks'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81:in `run_callbacks'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/persistable/destroyable.rb:24:in `destroy'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/contextual/mongo.rb:88:in `block in destroy'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/contextual/mongo.rb:667:in `yield_document'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/contextual/mongo.rb:122:in `block in each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:45:in `block in each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `block in each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongo-2.4.3/lib/mongo/cursor.rb:111:in `each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongo-2.4.3/lib/mongo/collection/view/iterable.rb:44:in `each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/query_cache.rb:207:in `each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/contextual/mongo.rb:121:in `each'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/contextual/mongo.rb:87:in `destroy'
/home/username/.rvm/gems/ruby-2.4.1@20170403_username_errbit_gemset/gems/mongoid-5.0.2/lib/mongoid/contextual.rb:20:in `destroy_all'
/mnt/username/installs/errbit/lib/tasks/errbit/database.rake:44:in `block (2 levels) in <top (required)>'
/home/username/.rvm/gems/ruby-2.4.1@global/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => errbit:cleanup
(See full trace by running task with --trace)
[07:46][username@hostname:errbit(master)]$ 
```
Could you please let me know how to fix this issue?

**Comment by compengsamit** [comment]
Is there any update on this issue?

**Comment by stevecrozz** [comment]
Thanks for the reminder @compengsamit, can you provide the git sha1 you're using?

**Comment by compengsamit** [comment]
The git sha1 is dc82cf6caedd17a9e1a0d410cdb1845366acd761
Please check and let me know what can be the issue here

**Comment by stevecrozz** [comment]
I'm not actually seeing a cleanup task. When I use that git sha1, I get
```bash
bundle exec rake errbit:cleanup
rake aborted!
Don't know how to build task 'errbit:cleanup' (see --tasks)
```

I see errbit:clear_outdated and clear_resolved...

Can you point me to the documentation you're following?
