### ISSUE TITLE
LoadError: Unable to autoload constant AirbrakeApi::V3::NoticeParser

### ISSUE THREAD

**Issue by cdrapier** [errbit/errbit#1308]
### Environment:

  * Errbit version: 88782035
  * OS: heroku-16

### Problem Description:

On some notices' POST, maybe in the specific case where the notices submission are parallel, we get an internal error such as this one:

```
LoadError: Unable to autoload constant AirbrakeApi::V3::NoticeParser, expected /app/lib/airbrake_api/v3/notice_parser.rb to define it
```

```
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:495→ load_missing_constant
--
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/dependencies.rb:184→ const_missing
[PROJECT_ROOT]/controllers/api/v3/notices_controller.rb:19→ create
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/implicit_render.rb:4→ send_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:198→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rendering.rb:10→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:20→ block in process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:117→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:555→ block (2 levels) in compile
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:505→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:92→ __run_callbacks__
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778→ _run_process_action_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81→ run_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/callbacks.rb:19→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rescue.rb:29→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:32→ block in process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164→ block in instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications/instrumenter.rb:20→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/notifications.rb:164→ instrument
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/instrumentation.rb:30→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/params_wrapper.rb:250→ process_action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/abstract_controller/base.rb:137→ process
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionview-4.2.9/lib/action_view/rendering.rb:30→ process
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal.rb:196→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal/rack_delegation.rb:13→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_controller/metal.rb:237→ block in action
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:74→ dispatch
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:43→ serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:43→ block in serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30→ each
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/journey/router.rb:30→ serve
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/routing/route_set.rb:817→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186→ call!
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186→ call!
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:36→ block in call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35→ catch
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/warden-1.2.7/lib/warden/manager.rb:35→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/etag.rb:24→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/conditionalget.rb:38→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/head.rb:13→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/params_parser.rb:27→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/flash.rb:260→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225→ context
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/cookies.rb:560→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:29→ block in call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:88→ __run_callbacks__
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:778→ _run_call_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/callbacks.rb:81→ run_callbacks
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/callbacks.rb:27→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/remote_ip.rb:78→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/debug_exceptions.rb:17→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/show_exceptions.rb:30→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:38→ call_app
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:20→ block in call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68→ block in tagged
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:26→ tagged
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/tagged_logging.rb:68→ tagged
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/rack/logger.rb:20→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/request_store-1.1.0/lib/request_store/middleware.rb:8→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/request_id.rb:21→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/methodoverride.rb:22→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/runtime.rb:18→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.9/lib/active_support/cache/strategy/local_cache_middleware.rb:28→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.9/lib/action_dispatch/middleware/static.rb:120→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/sendfile.rb:113→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails/engine.rb:518→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/railties-4.2.9/lib/rails[PROJECT_ROOT]lication.rb:165→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/rack-1.6.8/lib/rack/deflater.rb:35→ call
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/configuration.rb:224→ call

[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:600→ handle_request
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:435→ process_client
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/server.rb:299→ block in run
[PROJECT_ROOT]/vendor/bundle/ruby/2.3.0/gems/puma-3.8.2/lib/puma/thread_pool.rb:120→ block in spawn_thread
```

And here are some logs:

```
2018-07-18T02:58:20.727281+00:00 app[web.1]: Completed 201 Created in 989ms (Views: 0.3ms)
2018-07-18T02:58:20.731695+00:00 heroku[router]: at=info method=POST path="/api/v3/projects/1/notices" host=mw-errbit.herokuapp.com request_id=33b714d0-722b-42e5-9092-9e3855a28231 fwd="54.248.88.219" dyno=web.1 connect=0ms service=1023ms status=201 bytes=683 protocol=https
2018-07-18T02:58:20.822936+00:00 heroku[router]: at=info method=POST path="/api/v3/projects/1/notices" host=mw-errbit.herokuapp.com request_id=cf2e9cce-b2a0-430f-9f8d-b6b4a457d65a fwd="52.69.74.146" dyno=web.1 connect=0ms service=931ms status=500 bytes=715 protocol=https
2018-07-18T02:58:20.933603+00:00 heroku[router]: at=info method=POST path="/api/v3/projects/1/notices" host=mw-errbit.herokuapp.com request_id=a0250d02-2a78-4739-b92d-fd6ef932a802 fwd="52.69.74.146" dyno=web.1 connect=1ms service=1186ms status=500 bytes=715 protocol=https
2018-07-18T02:58:20.821912+00:00 app[web.1]:
2018-07-18T02:58:20.821929+00:00 app[web.1]: RuntimeError (Circular dependency detected while autoloading constant Hoptoad):
2018-07-18T02:58:20.821931+00:00 app[web.1]: app/models/error_report.rb:31:in `initialize'
2018-07-18T02:58:20.821933+00:00 app[web.1]: lib/overrides/hoptoad_notifier/hoptoad_notifier.rb:17:in `new'
2018-07-18T02:58:20.821934+00:00 app[web.1]: lib/overrides/hoptoad_notifier/hoptoad_notifier.rb:17:in `send_notice'
2018-07-18T02:58:20.821937+00:00 app[web.1]:
2018-07-18T02:58:20.821936+00:00 app[web.1]:
2018-07-18T02:58:20.876588+00:00 app[web.1]: RuntimeError (Circular dependency detected while autoloading constant Hoptoad):
2018-07-18T02:58:20.876583+00:00 app[web.1]:
2018-07-18T02:58:20.876589+00:00 app[web.1]: app/models/error_report.rb:31:in `initialize'
2018-07-18T02:58:20.876591+00:00 app[web.1]: lib/overrides/hoptoad_notifier/hoptoad_notifier.rb:17:in `new'
2018-07-18T02:58:20.876593+00:00 app[web.1]: lib/overrides/hoptoad_notifier/hoptoad_notifier.rb:17:in `send_notice'
2018-07-18T02:58:20.876594+00:00 app[web.1]:
2018-07-18T02:58:20.876596+00:00 app[web.1]:
2018-07-18T02:58:21.186065+00:00 app[web.1]: Internal error was logged to 'Self.Errbit' app.
2018-07-18T02:58:21.186981+00:00 app[web.1]:
2018-07-18T02:58:21.186986+00:00 app[web.1]: LoadError (Unable to autoload constant AirbrakeApi::V3::NoticeParser, expected /app/lib/airbrake_api/v3/notice_parser.rb to define it):
2018-07-18T02:58:21.186989+00:00 app[web.1]: app/controllers/api/v3/notices_controller.rb:19:in `create'
2018-07-18T02:58:21.186990+00:00 app[web.1]:
2018-07-18T02:58:21.186992+00:00 app[web.1]:
2018-07-18T02:58:21.251721+00:00 app[web.1]: Completed 201 Created in 1472ms (Views: 0.2ms)
2018-07-18T02:58:21.275871+00:00 app[web.1]: Completed 201 Created in 753ms (Views: 0.3ms)
2018-07-18T02:58:21.382771+00:00 app[web.1]: Completed 201 Created in 1531ms (Views: 0.5ms)
```

Not sure if the Hoptoad Curcular dependency problem is related, we Have other of the "Unable to autoload constant AirbrakeApi::V3::NoticeParser" without that other one.

**Comment by rud** [comment]
Thank you for reporting this, should fortunately be a fairly simple fix. Usually this is caused by using auto-loading instead of eager-loading in a multi-threaded server. Only eager-loading works in that case. 

Anyone willing to take a stab at a PR changing this part of the class-loading strategy?
