### ISSUE TITLE
uninitialized class variable @@schemes in v0.9.0

### ISSUE THREAD

**Issue by masterkain** [errbit/errbit#1470]
hello,
I'm testing docker image v0.9.0, it starts but I have this issue opening the rails console:

```
Traceback (most recent call last):
	36: from bin/rails:29:in `<main>'
	35: from bin/rails:29:in `load'
	34: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/bin/rails:9:in `<top (required)>'
	33: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/bin/rails:9:in `require'
	32: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/cli.rb:5:in `<top (required)>'
	31: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/app_rails_loader.rb:34:in `exec_app_rails'
	30: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/app_rails_loader.rb:34:in `loop'
	29: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/app_rails_loader.rb:45:in `block in exec_app_rails'
	28: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/app_rails_loader.rb:45:in `require'
	27: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands.rb:17:in `<top (required)>'
	26: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	25: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:67:in `console'
	24: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	23: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails/commands/commands_tasks.rb:141:in `require'
	22: from /app/config/application.rb:3:in `<top (required)>'
	21: from /app/config/application.rb:3:in `require'
	20: from /usr/local/bundle/ruby/2.5.0/gems/actionpack-4.2.11.1/lib/action_controller/railtie.rb:1:in `<top (required)>'
	19: from /usr/local/bundle/ruby/2.5.0/gems/actionpack-4.2.11.1/lib/action_controller/railtie.rb:1:in `require'
	18: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails.rb:15:in `<top (required)>'
	17: from /usr/local/bundle/ruby/2.5.0/gems/railties-4.2.11.1/lib/rails.rb:15:in `require'
	16: from /usr/local/bundle/ruby/2.5.0/gems/actionpack-4.2.11.1/lib/action_dispatch/railtie.rb:1:in `<top (required)>'
	15: from /usr/local/bundle/ruby/2.5.0/gems/actionpack-4.2.11.1/lib/action_dispatch/railtie.rb:1:in `require'
	14: from /usr/local/bundle/ruby/2.5.0/gems/actionpack-4.2.11.1/lib/action_dispatch.rb:29:in `<top (required)>'
	13: from /usr/local/bundle/ruby/2.5.0/gems/actionpack-4.2.11.1/lib/action_dispatch.rb:29:in `require'
	12: from /usr/local/bundle/ruby/2.5.0/gems/rack-1.6.13/lib/rack.rb:12:in `<top (required)>'
	11: from /usr/local/bundle/ruby/2.5.0/gems/rack-1.6.13/lib/rack.rb:95:in `<module:Rack>'
	10: from /usr/local/bundle/ruby/2.5.0/gems/rack-1.6.13/lib/rack.rb:95:in `require'
	 9: from /usr/local/bundle/ruby/2.5.0/gems/rack-1.6.13/lib/rack/utils.rb:17:in `<top (required)>'
	 8: from /usr/local/bundle/ruby/2.5.0/gems/rack-1.6.13/lib/rack/utils.rb:17:in `require'
	 7: from /usr/local/lib/ruby/2.5.0/uri/common.rb:13:in `<top (required)>'
	 6: from /usr/local/lib/ruby/2.5.0/uri/common.rb:13:in `require'
	 5: from /usr/local/lib/ruby/2.5.0/uri/rfc2396_parser.rb:13:in `<top (required)>'
	 4: from /usr/local/lib/ruby/2.5.0/uri/rfc2396_parser.rb:13:in `require'
	 3: from /usr/local/lib/ruby/2.5.0/uri.rb:107:in `<top (required)>'
	 2: from /usr/local/lib/ruby/2.5.0/uri.rb:107:in `require'
	 1: from /usr/local/lib/ruby/2.5.0/uri/ftp.rb:13:in `<top (required)>'
/usr/local/lib/ruby/2.5.0/uri/ftp.rb:266:in `<module:URI>': uninitialized class variable @@schemes in URI (NameError)
```

**Comment by stevecrozz** [comment]
Thanks for the report @masterkain . It looks like we may need to upgrade the version of Ruby we use to build these docker images.

**Comment by stevecrozz** [comment]
I don't understand the cause of this issue, but I have reproduced it. The fix from your stackoverflow of adding require 'uri' to the top of application.rb works, but I still don't understand it. I'm reluctant to make a change without understanding the issue. I'd love to hear an explanation if anyone can come up with one.

**Comment by masterkain** [comment]
yeah that seems weird, however, if it may help at all, I've found the ruby 2.6.x series very stable across a large number of apps I have deployed, might be worth a try.

the only thing I recall when using the 2.6 image is that BUNDLE_PATH has some change: https://github.com/rubygems/bundler/issues/7531#issuecomment-575930361
