### ISSUE TITLE
Heroku Fails to Deploy - MongoDB Host Issue

### ISSUE THREAD

**Issue by Coolguy3289** [errbit/errbit#1471]
### Step 1: Are you in the right place?

  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged with errbit.
Yes

### Step 2: Describe your environment

  * Errbit version: 0.9.0
  * OS: Herku

### Step 3: Describe the problem:

Used deployment to Heroku and the scripts errored due to an issue with MongoDB and the specific server not matching reported hosts.

#### Steps to reproduce:

  1. Click Deploy to Heroku
  2. Fill App Name and Copy Name to HEROKU_APP_NAME variable
  3. Click Deploy button and wait for deployment to error (finish)

#### Observed Results:

``MONGODB | Removing server ds241288.mlab.com:41288 because it is not in hosts reported by primary ds241288.mlab.com:41288 (self-identified as ds241288-a.mlab.com:41288). Reported hosts are: ds241288-a.mlab.com:41288
rake aborted!``

#### Expected Results:

  A successful deployment to occur.

#### Application Logs:

```Overwriting existing field _id in class App.
Seeding database
-------------------------------
Creating an initial admin user:
-- email:    errbit@errbit.example.com
-- password: lHpgYI8UxsAK

Be sure to note down these credentials now!
MONGODB | Removing server ds241288.mlab.com:41288 because it is not in hosts reported by primary ds241288.mlab.com:41288 (self-identified as ds241288-a.mlab.com:41288). Reported hosts are: ds241288-a.mlab.com:41288
rake aborted!
Mongo::Error::OperationFailure: Mongo::Error::OperationFailure: Transaction numbers are only allowed on storage engines that support document-level locking (20) (on ds241288-a.mlab.com:41288, modern retry, attempt 1) This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string or use the retry_writes: false Ruby client option
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/result.rb:297:in `raise_operation_failure'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/result.rb:268:in `validate!'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:29:in `block (3 levels) in validate_result'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:28:in `block (2 levels) in validate_result'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:27:in `block in validate_result'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:26:in `validate_result'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/write.rb:44:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/collection.rb:548:in `block (2 levels) in insert_one'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/retryable.rb:220:in `write_with_retry'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/collection.rb:537:in `block in insert_one'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/client.rb:844:in `with_session'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/collection.rb:535:in `insert_one'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/query_cache.rb:182:in `insert_one_with_clear_cache'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:79:in `insert_as_root'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:27:in `block in insert'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:118:in `block (2 levels) in prepare_insert'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:117:in `block in prepare_insert'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:23:in `insert'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/savable.rb:23:in `save'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/savable.rb:44:in `save!'
/app/db/seeds.rb:41:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/app/vendor/bundle/bin/bundle:104:in `load'
/app/vendor/bundle/bin/bundle:104:in `<main>'

Caused by:
Mongo::Error::OperationFailure: Transaction numbers are only allowed on storage engines that support document-level locking (20) (on ds241288-a.mlab.com:41288, modern retry, attempt 1) (on ds241288-a.mlab.com:41288, modern retry, attempt 1)
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/result.rb:297:in `raise_operation_failure'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/result.rb:268:in `validate!'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:29:in `block (3 levels) in validate_result'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:87:in `add_server_diagnostics'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:28:in `block (2 levels) in validate_result'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:43:in `add_error_labels'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:27:in `block in validate_result'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:73:in `unpin_maybe'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/response_handling.rb:26:in `validate_result'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/operation/shared/write.rb:44:in `execute'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/collection.rb:548:in `block (2 levels) in insert_one'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/retryable.rb:220:in `write_with_retry'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/collection.rb:537:in `block in insert_one'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/client.rb:844:in `with_session'
/app/vendor/bundle/ruby/2.5.0/gems/mongo-2.11.3/lib/mongo/collection.rb:535:in `insert_one'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/query_cache.rb:182:in `insert_one_with_clear_cache'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:79:in `insert_as_root'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:27:in `block in insert'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:118:in `block (2 levels) in prepare_insert'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:117:in `block in prepare_insert'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:117:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:505:in `call'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/interceptable.rb:138:in `run_callbacks'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:116:in `prepare_insert'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/creatable.rb:23:in `insert'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/savable.rb:23:in `save'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/persistable/savable.rb:44:in `save!'
/app/db/seeds.rb:41:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `block in load'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.5.0/gems/activesupport-4.2.11.1/lib/active_support/dependencies.rb:268:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/mongoid-5.4.1/lib/mongoid/railties/database.rake:20:in `block (2 levels) in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:74:in `kernel_load'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli/exec.rb:28:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:465:in `exec'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor.rb:387:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:27:in `dispatch'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/vendor/thor/lib/thor/base.rb:466:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/cli.rb:18:in `start'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/exe/bundle:30:in `block in <top (required)>'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/lib/bundler/friendly_errors.rb:124:in `with_friendly_errors'
/app/vendor/bundle/ruby/2.5.0/gems/bundler-2.0.2/exe/bundle:22:in `<top (required)>'
/app/vendor/bundle/bin/bundle:104:in `load'
/app/vendor/bundle/bin/bundle:104:in `<main>'
Tasks: TOP => errbit:bootstrap => db:seed
(See full trace by running task with --trace)```

**Comment by stevecrozz** [comment]
Thanks for the report @Coolguy3289 . Are you able to fork errbit and try the suggestion about retryWrites?

**Comment by Coolguy3289** [comment]
I will attempt that now and report back

**Comment by Coolguy3289** [comment]
So uhhh, Where can I edit or append the connection string being obtained from mLabs?

**Comment by stevecrozz** [comment]
You could use the heroku cli to alter the environment variable. I can't remember the name of the variable they use, but it is one of (MONGODB_URI MONGOLAB_URI MONGOHQ_URL MONGODB_URL MONGO_URL) or you could probably add the option in: config/mongo.rb under the `options` section.

**Comment by Coolguy3289** [comment]
It's likely my inexperience with this, heroku and mongoid, but I'm continuously running into either a ruby build error because `retry_writes: false` isn't a valid configuration option for Mongoid (in Config/mongo.rb), and adding it in the load.rb doesn't seem to work correctly. Looking at the error again, it mentions adding `or use the retry_writes: false Ruby client option`
So with that in mind, where would that be appropriate to insert?

**Comment by stevecrozz** [comment]
Looks like you can either put it in the URI (?retryWrites=false), or in config/mongo.rb in the default client, right under `uri` as retry_writes: false.

If that works, I suppose I can add a note to the docs for the heroku deployment

**Comment by Coolguy3289** [comment]
Neither option worked, still getting the same error. Reached out to MLabs as well and this was the response from them:
http://pomf.thegamingcorner.net/files/kgnedl.png

**Comment by stevecrozz** [comment]
I'm not sure what to make of that, maybe you can get them to visit https://github.com/errbit/errbit, click the "deploy to heroku" button and figure it out.

I don't use heroku and they want my credit card (which I don't want to give them) before they'll deploy errbit for me so I'm not able to test this myself.

**Comment by Coolguy3289** [comment]
I was able to get a heroku instance running by manually creating an app, making a free MongoDB cluster through https://cloud.mongodb.com and using that URI to connect after adding an environment variable to the heroku instance. Would there be any contention if I were to just rewrite the heroku deployment docs to support what I did?

**Comment by stevecrozz** [comment]
That'd be nice and if the button doesn't work, we may as well remove it from the README file to keep others from running into the same issue and I guess we may as well remove the app.json file until somebody can fix it.

**Comment by Coolguy3289** [comment]
Well leave the app.json for now. I'll make a PR with the changes to both the README and docs. I may tweak the app.json because the auto-deploy from repo feature of heroku got me 95% of the way there. Only one other thing needed added to make it work and that was a manual MongoDB URI.

**Comment by ryanfb** [comment]
FWIW: I just ran into this same issue, and while adding `retry_writes: false` under `uri` in `config/mongo.rb` did not fix the problem for me, changing `uri: uri` to `uri: uri + '?retryWrites=false'` seems to have fixed it.
