### ISSUE TITLE
Cannot run errbit with Ruby 2.7.4

### ISSUE THREAD

**Issue by zedalaye** [errbit/errbit#1503]
### Step 1: Are you in the right place?

Seems so.

### Step 2: Describe your environment

  * Errbit version: upgrading to current HEAD
  * OS: Ubuntu 14.04, Ruby in installed using rbenv

### Step 3: Describe the problem:

```
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
deploy@errbit1[crisalid](errbit):/usr/local/webapps/errbit1/current$ bundle exec rake db:migrate
rake aborted!
NoMethodError: undefined method `new' for BigDecimal:Class
/usr/local/webapps/errbit1/current/config/application.rb:3:in `require'
/usr/local/webapps/errbit1/current/config/application.rb:3:in `<top (required)>'
/usr/local/webapps/errbit1/current/Rakefile:11:in `require'
/usr/local/webapps/errbit1/current/Rakefile:11:in `<top (required)>'
/home/deploy/.rbenv/versions/2.7.4/bin/bundle:23:in `load'
/home/deploy/.rbenv/versions/2.7.4/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
```

#### Steps to reproduce:

```
git pull origin master
bundle install
bundle exec rake db:migrate # crashes here

# never tried
rake db:mongoid:remove_undefined_indexes
rake db:mongoid:create_indexes
rake assets:precompile
```

**Comment by 2called-chaos** [comment]
We should maybe put this in the Readme but until the app (Rails 4) is updated the maximum Ruby version is 2.6.x

I run it on 2.6 for a while now. With 2.7 BigDecimal.new was removed and this doesn't work with ActiveRecord 4 (and probably other places in Rails as well)

**Comment by zedalaye** [comment]
It may be circomvented by pinning bigdecimal ? https://github.com/ruby/bigdecimal#which-version-should-you-select

**Comment by stevecrozz** [comment]
I'm open to a PR if it is easy to get Ruby 2.7 running, but ultimately we're going to need a rails upgrade if we want this project to continue. #1413

**Comment by lrjbrual** [comment]
Having trouble also deploying to Heroku. this project seems nice, but need to update. I'm trying to implement with our production environment so we can monitor multiple projects we have, but seems this is not updated, any plan to updated in the near future? thanks @stefanchrobot @zedalaye

**Comment by stevecrozz** [comment]
@lrjbrual We have a PR that claims to add Ruby 2.7 support at #1508. I haven't tested it yet, but you are welcome to try it. Let me know how it goes if you do.
