### ISSUE TITLE
i use this command ---> knife ssl check and this error occur please help  

### ISSUE THREAD

**Issue by SHIVAMRAWAT12** [errbit/errbit#1538]
root@ip-172-31-9-21:/home/ubuntu/chef-repo/.chef# knife ssl check
/opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/proxifier-1.0.3/lib/uri/socks.rb:8:in `<module:URI>': uninitialized class variable @@schemes in URI (NameEr                       ror)
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/proxifier-1.0.3/lib/uri/socks.rb:3:in `<top (required)>'
        from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/proxifier-1.0.3/lib/proxifier.rb:2:in `<top (required)>'
        from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/chef-18.0.185/lib/chef/mixin/proxified_socket.rb:18:in `<top (required)>'
        from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from <internal:/opt/chef-workstation/embedded/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/knife-18.0.185/lib/chef/knife/ssl_check.rb:33:in `block in <class:SslCheck>'
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/knife-18.0.185/lib/chef/knife.rb:245:in `each'
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/knife-18.0.185/lib/chef/knife.rb:245:in `load_deps'
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/knife-18.0.185/lib/chef/knife.rb:230:in `run'
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/knife-18.0.185/lib/chef/application/knife.rb:165:in `run'
        from /opt/chef-workstation/embedded/lib/ruby/gems/3.1.0/gems/knife-18.0.185/bin/knife:24:in `<top (required)>'
        from /usr/bin/knife:400:in `load'
        from /usr/bin/knife:400:in `<main>'

**Comment by burnettk** [comment]
hi @SHIVAMRAWAT12 , it's not obvious from your stack trace that errbit is involved, but if it is, you might take a look at https://github.com/errbit/errbit/issues/1470, as there is a workaround discussed there about shoving `require 'uri'` at the top of `config/application.rb`.

**Comment by Arametheus** [comment]
the error is actually a bug in chef-workstation here is the reference. [Github Error Ref.](https://github.com/chef/chef-workstation/issues/3072) hopefully they fix it soon.

**Comment by gs89745** [comment]
i am facing the same error @Arametheus while using knife ssl check command on my workstation.
