### ISSUE TITLE
Devise.secret_key was not set

### ISSUE THREAD

**Issue by jirikolarik** [errbit/errbit#580]
Hi, I have problem with first deploy. It say's Devise.secret_key was not set. Please add the following to your Devise initializer:

I think it should be loaded automatically from secret_token.rb, is it right?

```
  * 2013-10-10 21:27:12 executing `deploy:migrate'
  * executing "cd /var/www/errbit/releases/20131010192708 && bundle exec rake RAILS_ENV=production  db:migrate"
    servers: ["errbit.imin.cz"]
    [errbit.imin.cz] executing command
 ** [out :: errbit.imin.cz] rake aborted!
 ** [out :: errbit.imin.cz] Devise.secret_key was not set. Please add the following to your Devise initializer:
 ** [out :: errbit.imin.cz] 
 ** [out :: errbit.imin.cz] config.secret_key = '98a49a74e6e453c243216dd1be3b130015c70dd6328b9f513e93d2ef1c96faf9ef329f98426f0b990d80a1a97e13f1880e5f408f47a982a006350dd8290413c6'
 ** [out :: errbit.imin.cz] 
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/devise-3.1.0/lib/devise/rails/routes.rb:440:in `raise_no_secret_key'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/devise-3.1.0/lib/devise/rails/routes.rb:195:in `devise_for'
 ** [out :: errbit.imin.cz] /var/www/errbit/releases/20131010192708/config/routes.rb:3:in `block in <top (required)>'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:285:in `instance_exec'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:285:in `eval_block'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/actionpack-3.2.14/lib/action_dispatch/routing/route_set.rb:263:in `draw'
 ** [out :: errbit.imin.cz] /var/www/errbit/releases/20131010192708/config/routes.rb:1:in `<top (required)>'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `load'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `block in load'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:245:in `load'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
 ** [out :: errbit.imin.cz] 
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application/routes_reloader.rb:40:in `each'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application/routes_reloader.rb:40:in `load_paths'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application/routes_reloader.rb:16:in `reload!'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application/routes_reloader.rb:26:in `block in updater'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/file_update_checker.rb:78:in `call'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/file_update_checker.rb:78:in `execute'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application/routes_reloader.rb:27:in `updater'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application/finisher.rb:66:in `block in <module:Finisher>'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:30:in `instance_exec'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:30:in `run'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:55:in `block in run_initializers'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:54:in `each'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/initializable.rb:54:in `run_initializers'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application.rb:136:in `initialize!'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/railtie/configurable.rb:30:in `method_missing'
 ** [out :: errbit.imin.cz] /var/www/errbit/releases/20131010192708/config/environment.rb:5:in `<top (required)>'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `block in require'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:236:in `load_dependency'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/activesupport-3.2.14/lib/active_support/dependencies.rb:251:in `require'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application.rb:103:in `require_environment!'
 ** [out :: errbit.imin.cz] /var/www/errbit/shared/bundle/ruby/2.0.0/gems/railties-3.2.14/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
 ** [out :: errbit.imin.cz] Tasks: TOP => db:migrate => environment
 ** [out :: errbit.imin.cz] (See full trace by running task with --trace)
```

**Comment by spotscale** [comment]
Can you explain more clearly how this was fixed?
