### ISSUE TITLE
can't find any asset

### ISSUE THREAD

**Issue by abacha** [errbit/errbit#767]
I've deployed using capistrano following the readme but it doesn't load any asset
I keep getting route errors on my log:

````
ActionController::RoutingError (No route matches [GET] "/assets/thumbs-up-8ddf7e617d72050d03b421742f7f825a.png"):
  actionpack (3.2.21) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (3.2.21) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.21) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.21) lib/rails/rack/logger.rb:16:in `block in call'
....
````

**Comment by arthurnn** [comment]
I guess gem was reverted already.. so closing this
