### ISSUE TITLE
Can't view errors or edit apps after Errbit upgrade

### ISSUE THREAD

**Issue by organicweb** [errbit/errbit#878]
Here's the errors I received via email : 
ERROR MESSAGE:
Moped::Errors::OperationFailure: The operation: #<Moped::Protocol::Command @length=81 @request_id=88 @response_to=0 @op_code=2004 @flags=[] @full_collection_name="errbit_production.$cmd" @skip=0 @limit=-1 @selector={:getlasterror=>1, :w=>1} @fields=nil> failed with error "Invalid modifier specified $unset"

WHERE:
apps#edit

app/controllers/apps_controller.rb:111
app/controllers/apps_controller.rb:78

URL:
http://errbit.ledez.net/apps/50b71893ba9f111c02000002/edit

BROWSER:
100.0%	Firefox 37.0 (OS X 10.7)

FULL BACKTRACE:
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/operation/read.rb:50
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:594
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:594
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:593
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:593
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:617
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/notifications.rb:159
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/notifications/instrumenter.rb:20
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/notifications.rb:159
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/instrumentable.rb:31
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:616
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:587
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:358
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/operation/write.rb:47
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:665
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:502
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/query.rb:427
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/cluster.rb:249
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:204
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/executable.rb:25
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/node.rb:203
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/cluster.rb:248
[GEM_ROOT]/gems/moped-2.0.4/lib/moped/query.rb:426
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/query_cache.rb:117
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/persistable/deletable.rb:65
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/persistable/deletable.rb:25
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/persistable/deletable.rb:115
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/persistable/deletable.rb:23
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/persistable/destroyable.rb:24
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:82
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/interceptable.rb:138
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/persistable/destroyable.rb:24
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/relations/embedded/one.rb:43
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/relations/accessors.rb:231
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/relations/accessors.rb:140
[GEM_ROOT]/gems/mongoid-4.0.2/lib/mongoid/relations/accessors.rb:229
app/controllers/apps_controller.rb:111
app/controllers/apps_controller.rb:78
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal/implicit_render.rb:4
[GEM_ROOT]/gems/actionpack-4.1.10/lib/abstract_controller/base.rb:189
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal/rendering.rb:10
[GEM_ROOT]/gems/actionpack-4.1.10/lib/abstract_controller/callbacks.rb:20
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:113
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:113
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:552
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:502
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:502
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:86
[GEM_ROOT]/gems/actionpack-4.1.10/lib/abstract_controller/callbacks.rb:19
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal/rescue.rb:29
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal/instrumentation.rb:32
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/notifications.rb:159
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/notifications/instrumenter.rb:20
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/notifications.rb:159
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal/instrumentation.rb:30
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal/params_wrapper.rb:250
[GEM_ROOT]/gems/actionpack-4.1.10/lib/abstract_controller/base.rb:136
[GEM_ROOT]/gems/actionview-4.1.10/lib/action_view/rendering.rb:30
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal.rb:196
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal/rack_delegation.rb:13
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_controller/metal.rb:232
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/routing/route_set.rb:82
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/routing/route_set.rb:82
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/routing/route_set.rb:50
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/journey/router.rb:73
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/journey/router.rb:59
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/journey/router.rb:59
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/routing/route_set.rb:692
[GEM_ROOT]/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186
[GEM_ROOT]/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164
[GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb:35
[GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb:34
[GEM_ROOT]/gems/warden-1.2.3/lib/warden/manager.rb:34
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/etag.rb:23
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/conditionalget.rb:25
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/head.rb:11
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/params_parser.rb:27
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/flash.rb:254
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/cookies.rb:562
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/callbacks.rb:29
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/callbacks.rb:82
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/callbacks.rb:27
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/remote_ip.rb:76
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/debug_exceptions.rb:17
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/show_exceptions.rb:30
[GEM_ROOT]/gems/railties-4.1.10/lib/rails/rack/logger.rb:38
[GEM_ROOT]/gems/railties-4.1.10/lib/rails/rack/logger.rb:20
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/tagged_logging.rb:68
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/tagged_logging.rb:26
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/tagged_logging.rb:68
[GEM_ROOT]/gems/railties-4.1.10/lib/rails/rack/logger.rb:20
[GEM_ROOT]/gems/request_store-1.1.0/lib/request_store/middleware.rb:8
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/request_id.rb:21
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/methodoverride.rb:21
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/runtime.rb:17
[GEM_ROOT]/gems/activesupport-4.1.10/lib/active_support/cache/strategy/local_cache_middleware.rb:26
[GEM_ROOT]/gems/actionpack-4.1.10/lib/action_dispatch/middleware/static.rb:84
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/sendfile.rb:112
[GEM_ROOT]/gems/railties-4.1.10/lib/rails/engine.rb:514
[GEM_ROOT]/gems/railties-4.1.10/lib/rails/application.rb:144
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/deflater.rb:25
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/lint.rb:49
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/lint.rb:37
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/showexceptions.rb:24
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/commonlogger.rb:33
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/chunked.rb:43
[GEM_ROOT]/gems/rack-1.5.2/lib/rack/content_length.rb:14
[GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:580
[GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:674
[GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:529
[GEM_ROOT]/gems/unicorn-4.9.0/lib/unicorn/http_server.rb:140
[GEM_ROOT]/gems/unicorn-4.9.0/bin/unicorn:126
[GEM_ROOT]/bin/unicorn:23
[GEM_ROOT]/bin/unicorn:23

Log stack : 

**Edit an app** : 
I, [2015-05-05T11:06:49.050738 #410]  INFO -- : Started GET "/apps/5547a42d6769745f55010000/edit" for 88.174.118.112 at 2015-05-05 11:06:49 +0200
I, [2015-05-05T11:06:49.070375 #410]  INFO -- : Processing by AppsController#edit as HTML
I, [2015-05-05T11:06:49.070465 #410]  INFO -- :   Parameters: {"id"=>"5547a42d6769745f55010000"}
I, [2015-05-05T11:06:49.097405 #410]  INFO -- : Completed 500 Internal Server Error in 27ms
I, [2015-05-05T11:06:49.428856 #410]  INFO -- : Internal error was logged to 'Self.Errbit' app.
F, [2015-05-05T11:06:49.430067 #410] FATAL -- :
Moped::Errors::OperationFailure (The operation: #<Moped::Protocol::Command
  @length=81
  @request_id=5
  @response_to=0
  @op_code=2004
  @flags=[]
  @full_collection_name="errbit_production.$cmd"
  @skip=0
  @limit=-1
  @selector={:getlasterror=>1, :w=>1}
  @fields=nil>
failed with error "Invalid modifier specified $unset"):
  app/controllers/apps_controller.rb:111:in `plug_params'
  app/controllers/apps_controller.rb:78:in `edit'

**View error detail** :
I, [2015-05-05T11:08:10.945125 #407]  INFO -- : Started GET "/apps/50b8baabba9f114e8f000012/problems/524c105cba9f11017b000728" for 88.174.118.112 at 2015-05-05 11:08:10 +0200
I, [2015-05-05T11:08:10.946963 #407]  INFO -- : Processing by ProblemsController#show as HTML
I, [2015-05-05T11:08:10.947018 #407]  INFO -- :   Parameters: {"app_id"=>"50b8baabba9f114e8f000012", "id"=>"524c105cba9f11017b000728"}
I, [2015-05-05T11:08:10.949725 #407]  INFO -- : Completed 404 Not Found in 3ms
F, [2015-05-05T11:08:11.016138 #407] FATAL -- :
Mongoid::Errors::DocumentNotFound (
Problem:
  Document(s) not found for class App with id(s) 50b8baabba9f114e8f000012.
Summary:
  When calling App.find with an id or array of ids, each parameter must match a document in the database or this error will be raised. The search was for the id(s): 50b8baabba9f114e8f000012 ... (1 total) and the following ids were not found: 50b8baabba9f114e8f000012.
Resolution:
  Search for an id that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single id, or only the matched documents when searching for multiples.):
  app/controllers/problems_controller.rb:21:in `block in <class:ProblemsController>'
  app/controllers/problems_controller.rb:25:in `block in <class:ProblemsController>'
  app/controllers/problems_controller.rb:53:in `show'

I've tried to upgrade package for mongodb, but nothing seems to be working. Any help would be appreciated.

**Comment by stevecrozz** [comment]
@organicweb Can you tell me the version of errbit you're using? git sha1 would be great

**Comment by stevecrozz** [comment]
Also, can you tell me which version you were running before the upgrade and whether or not you have run the migrations?

**Comment by organicweb** [comment]
Hey Steve, here's I think the SHA1 (git rev-parse HEAD) : 
149ee30b33549e6a28f814896d413e961a5769f4

We were on 0.3 version and we've updated to master.
It's running on a ubuntu 10.04 LTS, all packages are up to date.
Migration have been done.
I've tried to dump database and run iron a fresh and clean install and it's still the same problem.

Thanks helping me

**Comment by stevecrozz** [comment]
What version of mongo are you using? It looks like your version doesn't support $unset

**Comment by stevecrozz** [comment]
Closing for lack of activity. Please reopen if you want to continue working through this or join me in https://gitter.im/errbit/errbit

**Comment by organicweb** [comment]
Oops sorry, completely forgot that problem !!

a-errbit@git:/usr/bin$ mongod --version
db version v1.2.2, pdfile version 4.5
Fri Sep  4 09:39:12 git version: nogitversion

Thx

**Comment by stevecrozz** [comment]
@organicweb mongo v1.2.2 is not a supported version of Errbit. Can you upgrade to v2.6+ ?
