### ISSUE TITLE
Backtraces show different paths in Errbit than in Airbrake

### ISSUE THREAD

**Issue by raulsann** [errbit/errbit#960]
Hi,

When using:

    Airbrake.notify(exception, airbrake_request_data)

If I send the backtrace to Airbrake we see the following:

<img width="1266" alt="airbrake" src="https://cloud.githubusercontent.com/assets/541900/10339993/51ecb0f4-6d0e-11e5-84e2-c4bcecc72e67.png">

The same exception is seen in Errbit as:

<img width="959" alt="errbit" src="https://cloud.githubusercontent.com/assets/541900/10340011/638eee08-6d0e-11e5-8da3-74dcc27951d9.png">

As you can see the traces are completely different. In Errbit it is confusing to see a path as:

    app/controllers/users_controller.rbusers_controller.rb:26→ /

Is this because any configuration issue or because of an issue with Errbit?

Thanks!

**Comment by stevecrozz** [comment]
@raulsann can you make sure you're using the latest errbit? This bug should have been fixed as of https://github.com/errbit/errbit/issues/942

If you're still seeing the problem can you tell me the git sha1 you are using?

**Comment by raulsann** [comment]
I see....

Thank you Steve. I just pulled from master and this is what I get:

```
Overwriting existing field _id in class App.
Creating scope :page. Overwriting existing method NotificationServices::CampfireService.page.
Creating scope :page. Overwriting existing method NotificationServices::FlowdockService.page.
Creating scope :page. Overwriting existing method NotificationServices::GtalkService.page.
Creating scope :page. Overwriting existing method NotificationServices::HipchatService.page.
Creating scope :page. Overwriting existing method NotificationServices::HoiioService.page.
Creating scope :page. Overwriting existing method NotificationServices::HubotService.page.
Creating scope :page. Overwriting existing method NotificationServices::PushoverService.page.
Creating scope :page. Overwriting existing method NotificationServices::SlackService.page.
Creating scope :page. Overwriting existing method NotificationServices::WebhookService.page.
/app/app/controllers/site_config_controller.rb:15:in `private': nil is not a symbol (TypeError)
	from /app/app/controllers/site_config_controller.rb:15:in `<class:SiteConfigController>'
	from /app/app/controllers/site_config_controller.rb:1:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:360:in `require_or_load'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:317:in `depend_on'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:233:in `require_dependency'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:472:in `block (2 levels) in eager_load!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:471:in `each'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:471:in `block in eager_load!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:469:in `each'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:469:in `eager_load!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/engine.rb:346:in `eager_load!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:56:in `each'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:56:in `block in <module:Finisher>'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:150:in `block in tsort_each'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:183:in `block (2 levels) in each_strongly_connected_component'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:219:in `each_strongly_connected_component_from'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:182:in `block in each_strongly_connected_component'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:180:in `each'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:180:in `each_strongly_connected_component'
	from /app/vendor/ruby-2.0.0/lib/ruby/2.0.0/tsort.rb:148:in `tsort_each'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
	from /app/config/environment.rb:16:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/application.rb:328:in `require_environment!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:67:in `console'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.0.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:6:in `require'
	from bin/rails:6:in `<main>'
```

Since this error is not related to the issue of this thread I will keep looking for a solution and will reply back when I am able to test it out.

Thank you again, Steve!

**Comment by raulsann** [comment]
Sweet! I went back to #942 and it is solved. 

Thank you Steve!

**Comment by stevecrozz** [comment]
@raulsann I think the bug you found on master will disappear when you upgrade to Ruby 2.1 or higher.
