### ISSUE TITLE
500 error when an errbit error is generated

### ISSUE THREAD

**Issue by ajardan** [errbit/errbit#968]
```
2015-10-14_13:59:54.82069 Completed 500 Internal Server Error in 103ms
2015-10-14_13:59:54.87694 
2015-10-14_13:59:54.87696 Mongo::Error::OperationFailure (Invalid modifier specified $setOnInsert ()):
2015-10-14_13:59:54.87696   app/models/backtrace.rb:16:in `find_or_create'
2015-10-14_13:59:54.87697   app/models/error_report.rb:47:in `backtrace'
2015-10-14_13:59:54.87697   app/models/error_report.rb:67:in `make_notice'
2015-10-14_13:59:54.87698   app/models/error_report.rb:54:in `generate_notice!'
2015-10-14_13:59:54.87698   lib/overrides/hoptoad_notifier/hoptoad_notifier.rb:19:in `send_notice'
```

**Comment by stevecrozz** [comment]
@ajardan Can you verify that you're using mongo v2.6 or greater?

**Comment by ajardan** [comment]
@stevecrozz that's right, I upgraded Mongo to 3.0 and it works well. Thanks, and sorry.

**Comment by stevecrozz** [comment]
No prob. Glad you're up and running
